BAYER = "bayer"
PROPER = "proper"
MAG = "mag"
X = "x"
Y = "y"
DIST = "dist"

# Star Constants
Betelgeuse = "Betelgeuse"
Bellatrix = "Bellatrix"
Meissa = "Meissa"
Alnitak = "Alnitak"
Alnilam = "Alnilam"
Mintaka = "Mintaka"
Saiph = "Saiph"
Rigel = "Rigel"